### ISSUE TITLE
Merge Shape Elements into One Solid Shape

### ISSUE THREAD

**Issue by guti7** [downtownjakebrown/SwiftyIllustrator#1]
I'm working with logo designs converted into swift shapes. When I do this the shapes elements don't quite work together when I need to change the color or backgrounds as it becomes complex when the logo design results into a high count of swift shape elements. Do you know of a way to merge the shape elements into one solid shape? or any suggestions on how to approach this.

**Comment by downtownjakebrown** [comment]
Can you provide an example? I'm not sure I quite understand the issue.

But in general I'd say you could try:
1) Simplifying your AI drawing before exporting it by merging overlapping shapes of the same color (see, e.g., AI's [pathfinder tool](https://helpx.adobe.com/nz/illustrator/using/combining-objects.html))
2) Refactoring your code to organize shapes together into subviews, so as to keep each view's shape count under SwiftUI's 10 view/shape limit (I regularly do this in any case just to keep things organized)

**Comment by downtownjakebrown** [comment]
I'm going to go ahead and close this issue. If you are still having a problem, please open a new issue with more info or an example so I can address it. Thanks!

**Comment by downtownjakebrown** [comment]
I'm going to go ahead and close this issue. If you are still having a problem, please open a new issue with more info or an example so I can address it. Thanks!
